# Generated by Django 4.2.6 on 2024-08-07 06:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("Question", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="userresponse",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="userprompt",
            name="style",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="Question.style"
            ),
        ),
        migrations.AddField(
            model_name="userprompt",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="useranxietyscore",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="useranxietyresponse",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="Question.anxietyquestion",
            ),
        ),
        migrations.AddField(
            model_name="useranxietyresponse",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="style",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="Question.style"
            ),
        ),
        migrations.AddField(
            model_name="prompttemplate",
            name="style",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="Question.style"
            ),
        ),
    ]
